export const harnessOpenApiSpec = {
  openapi: "3.1.0",
  info: {
    title: "MinuNotes Harness API",
    version: "0.1.0",
    description: "Agent-focused API for scoped MinuNotes folder and note workflows.",
  },
  servers: [{ url: "/" }],
  security: [{ ApiKeyAuth: [] }],
  tags: [
    { name: "Folders" },
    { name: "Notes" },
    { name: "Tags" },
  ],
  paths: {
    "/api/harness/tags": {
      get: {
        tags: ["Tags"],
        operationId: "listTags",
        summary: "List tags",
        responses: { "200": { description: "Tags", content: { "application/json": { schema: { $ref: "#/components/schemas/TagsResponse" } } } }, "401": { $ref: "#/components/responses/Unauthorized" } },
      },
    },
    "/api/harness/folders": {
      get: {
        tags: ["Folders"],
        operationId: "listFolders",
        summary: "List accessible folders",
        responses: {
          "200": { description: "Folders visible to the API key", content: { "application/json": { schema: { $ref: "#/components/schemas/FoldersResponse" } } } },
          "401": { $ref: "#/components/responses/Unauthorized" },
        },
      },
      post: {
        tags: ["Folders"],
        operationId: "createFolder",
        summary: "Create a folder",
        description: "Requires the API key to have folder-creation permission. Created folders are automatically scoped to the same key.",
        requestBody: { required: true, content: { "application/json": { schema: { $ref: "#/components/schemas/CreateFolderRequest" } } } },
        responses: {
          "201": { description: "Created folder", content: { "application/json": { schema: { $ref: "#/components/schemas/FolderResponse" } } } },
          "400": { $ref: "#/components/responses/BadRequest" },
          "401": { $ref: "#/components/responses/Unauthorized" },
          "403": { $ref: "#/components/responses/Forbidden" },
        },
      },
    },
    "/api/harness/notes/search": {
      get: {
        tags: ["Notes"],
        operationId: "searchNotes",
        summary: "Search notes",
        parameters: [{ name: "q", in: "query", required: true, schema: { type: "string" } }, { name: "tag", in: "query", schema: { type: "string" } }],
        responses: { "200": { description: "Matching notes", content: { "application/json": { schema: { $ref: "#/components/schemas/SearchNotesResponse" } } } }, "401": { $ref: "#/components/responses/Unauthorized" } },
      },
    },
    "/api/harness/notes/orphans": {
      get: {
        tags: ["Notes"],
        operationId: "listOrphanNotes",
        summary: "List notes with no incoming links",
        responses: { "200": { description: "Orphan notes", content: { "application/json": { schema: { $ref: "#/components/schemas/SearchNotesResponse" } } } }, "401": { $ref: "#/components/responses/Unauthorized" } },
      },
    },
    "/api/harness/notes/search-lines": {
      get: {
        tags: ["Notes"],
        operationId: "searchNoteLines",
        summary: "Search matching lines across notes",
        parameters: [
          { name: "q", in: "query", required: true, schema: { type: "string" } },
          { name: "folderId", in: "query", schema: { type: "string" } },
          { name: "context", in: "query", schema: { type: "integer", minimum: 0 } },
          { name: "limit", in: "query", schema: { type: "integer", minimum: 1 } },
          { name: "caseSensitive", in: "query", schema: { type: "boolean" } },
        ],
        responses: { "200": { description: "Line matches", content: { "application/json": { schema: { $ref: "#/components/schemas/LineSearchResponse" } } } }, "401": { $ref: "#/components/responses/Unauthorized" } },
      },
    },
    "/api/harness/notes": {
      post: {
        tags: ["Notes"],
        operationId: "createNote",
        summary: "Create a note",
        requestBody: { required: true, content: { "application/json": { schema: { $ref: "#/components/schemas/CreateNoteRequest" } } } },
        responses: {
          "201": { description: "Created note", content: { "application/json": { schema: { $ref: "#/components/schemas/NoteResponse" } } } },
          "400": { $ref: "#/components/responses/BadRequest" },
          "401": { $ref: "#/components/responses/Unauthorized" },
          "403": { $ref: "#/components/responses/Forbidden" },
        },
      },
    },
    "/api/harness/notes/{noteId}": {
      get: {
        tags: ["Notes"],
        operationId: "getNote",
        summary: "Read a note",
        parameters: [{ $ref: "#/components/parameters/NoteId" }],
        responses: { "200": { description: "Note", content: { "application/json": { schema: { $ref: "#/components/schemas/NoteResponse" } } } }, "401": { $ref: "#/components/responses/Unauthorized" }, "403": { $ref: "#/components/responses/Forbidden" }, "404": { $ref: "#/components/responses/NotFound" } },
      },
    },
    "/api/harness/notes/{noteId}/tags": {
      get: {
        tags: ["Tags"],
        operationId: "listNoteTags",
        summary: "List note tags",
        parameters: [{ $ref: "#/components/parameters/NoteId" }],
        responses: { "200": { description: "Note tags", content: { "application/json": { schema: { $ref: "#/components/schemas/TagsResponse" } } } }, "401": { $ref: "#/components/responses/Unauthorized" }, "403": { $ref: "#/components/responses/Forbidden" }, "404": { $ref: "#/components/responses/NotFound" } },
      },
      put: {
        tags: ["Tags"],
        operationId: "updateNoteTags",
        summary: "Replace note tags",
        parameters: [{ $ref: "#/components/parameters/NoteId" }],
        requestBody: { required: true, content: { "application/json": { schema: { $ref: "#/components/schemas/UpdateTagsRequest" } } } },
        responses: { "200": { description: "Updated note tags", content: { "application/json": { schema: { $ref: "#/components/schemas/TagsResponse" } } } }, "400": { $ref: "#/components/responses/BadRequest" }, "401": { $ref: "#/components/responses/Unauthorized" }, "403": { $ref: "#/components/responses/Forbidden" }, "404": { $ref: "#/components/responses/NotFound" } },
      },
    },
    "/api/harness/notes/{noteId}/events": {
      get: {
        tags: ["Notes"],
        operationId: "listNoteEvents",
        summary: "List note events",
        parameters: [{ $ref: "#/components/parameters/NoteId" }, { name: "limit", in: "query", schema: { type: "integer", minimum: 1 } }],
        responses: { "200": { description: "Note events", content: { "application/json": { schema: { $ref: "#/components/schemas/NoteEventsResponse" } } } }, "401": { $ref: "#/components/responses/Unauthorized" }, "403": { $ref: "#/components/responses/Forbidden" }, "404": { $ref: "#/components/responses/NotFound" } },
      },
    },
    "/api/harness/notes/{noteId}/links": {
      get: {
        tags: ["Notes"],
        operationId: "listNoteLinks",
        summary: "List outgoing note links",
        description: "Returns links from the note, including unresolved wikilinks where targetNoteId is null.",
        parameters: [{ $ref: "#/components/parameters/NoteId" }],
        responses: { "200": { description: "Outgoing links", content: { "application/json": { schema: { $ref: "#/components/schemas/LinksResponse" } } } }, "401": { $ref: "#/components/responses/Unauthorized" }, "403": { $ref: "#/components/responses/Forbidden" }, "404": { $ref: "#/components/responses/NotFound" } },
      },
    },
    "/api/harness/notes/{noteId}/backlinks": {
      get: {
        tags: ["Notes"],
        operationId: "listNoteBacklinks",
        summary: "List backlinks to a note",
        description: "Returns notes that link to the target note with wikilinks or internal note URLs. Results are filtered to source notes visible to the current API key.",
        parameters: [{ $ref: "#/components/parameters/NoteId" }],
        responses: { "200": { description: "Note backlinks", content: { "application/json": { schema: { $ref: "#/components/schemas/BacklinksResponse" } } } }, "401": { $ref: "#/components/responses/Unauthorized" }, "403": { $ref: "#/components/responses/Forbidden" }, "404": { $ref: "#/components/responses/NotFound" } },
      },
    },
    "/api/harness/notes/{noteId}/lines": {
      get: {
        tags: ["Notes"],
        operationId: "readNoteLines",
        summary: "Read numbered note lines",
        parameters: [{ $ref: "#/components/parameters/NoteId" }, { name: "from", in: "query", schema: { type: "integer", minimum: 1 } }, { name: "to", in: "query", schema: { type: "integer", minimum: 1 } }],
        responses: { "200": { description: "Numbered lines", content: { "application/json": { schema: { $ref: "#/components/schemas/LinesResponse" } } } }, "401": { $ref: "#/components/responses/Unauthorized" }, "403": { $ref: "#/components/responses/Forbidden" }, "404": { $ref: "#/components/responses/NotFound" } },
      },
    },
    "/api/harness/notes/{noteId}/search-lines": {
      get: {
        tags: ["Notes"],
        operationId: "searchLinesInNote",
        summary: "Search matching lines in one note",
        parameters: [{ $ref: "#/components/parameters/NoteId" }, { name: "q", in: "query", required: true, schema: { type: "string" } }, { name: "context", in: "query", schema: { type: "integer", minimum: 0 } }, { name: "limit", in: "query", schema: { type: "integer", minimum: 1 } }, { name: "caseSensitive", in: "query", schema: { type: "boolean" } }],
        responses: { "200": { description: "Line matches", content: { "application/json": { schema: { $ref: "#/components/schemas/LineSearchResponse" } } } }, "401": { $ref: "#/components/responses/Unauthorized" }, "403": { $ref: "#/components/responses/Forbidden" }, "404": { $ref: "#/components/responses/NotFound" } },
      },
    },
    "/api/harness/notes/{noteId}/outline": {
      get: {
        tags: ["Notes"],
        operationId: "getNoteOutline",
        summary: "Get note outline",
        parameters: [{ $ref: "#/components/parameters/NoteId" }],
        responses: { "200": { description: "Note outline", content: { "application/json": { schema: { $ref: "#/components/schemas/OutlineResponse" } } } }, "401": { $ref: "#/components/responses/Unauthorized" }, "403": { $ref: "#/components/responses/Forbidden" }, "404": { $ref: "#/components/responses/NotFound" } },
      },
    },
    "/api/harness/notes/{noteId}/sections/{sectionId}": {
      get: {
        tags: ["Notes"],
        operationId: "readNoteSection",
        summary: "Read a note section",
        parameters: [{ $ref: "#/components/parameters/NoteId" }, { name: "sectionId", in: "path", required: true, schema: { type: "string" } }],
        responses: { "200": { description: "Note section", content: { "application/json": { schema: { $ref: "#/components/schemas/SectionResponse" } } } }, "401": { $ref: "#/components/responses/Unauthorized" }, "403": { $ref: "#/components/responses/Forbidden" }, "404": { $ref: "#/components/responses/NotFound" } },
      },
    },
    "/api/harness/notes/{noteId}/edit": {
      post: {
        tags: ["Notes"],
        operationId: "editNote",
        summary: "Edit a note",
        parameters: [{ $ref: "#/components/parameters/NoteId" }],
        requestBody: { required: true, content: { "application/json": { schema: { $ref: "#/components/schemas/EditNoteRequest" } } } },
        responses: { "200": { description: "Updated note", content: { "application/json": { schema: { $ref: "#/components/schemas/NoteResponse" } } } }, "400": { $ref: "#/components/responses/BadRequest" }, "401": { $ref: "#/components/responses/Unauthorized" }, "403": { $ref: "#/components/responses/Forbidden" }, "404": { $ref: "#/components/responses/NotFound" }, "409": { $ref: "#/components/responses/Conflict" } },
      },
    },
  },
  components: {
    securitySchemes: { ApiKeyAuth: { type: "apiKey", in: "header", name: "X-API-Key" } },
    parameters: { NoteId: { name: "noteId", in: "path", required: true, schema: { type: "string" } } },
    responses: {
      BadRequest: { description: "Bad request", content: { "application/json": { schema: { $ref: "#/components/schemas/ErrorResponse" } } } },
      Unauthorized: { description: "Missing or invalid API key", content: { "application/json": { schema: { $ref: "#/components/schemas/ErrorResponse" } } } },
      Forbidden: { description: "API key lacks required permission", content: { "application/json": { schema: { $ref: "#/components/schemas/ErrorResponse" } } } },
      NotFound: { description: "Resource not found", content: { "application/json": { schema: { $ref: "#/components/schemas/ErrorResponse" } } } },
      Conflict: { description: "Stale base hash or edit conflict", content: { "application/json": { schema: { $ref: "#/components/schemas/ErrorResponse" } } } },
    },
    schemas: {
      ErrorResponse: { type: "object", required: ["error"], properties: { error: { type: "string" } } },
      Folder: { type: "object", required: ["id", "parentFolderId", "title", "isPrivate", "isAgentReadOnly", "createdAt", "updatedAt"], properties: { id: { type: "string" }, parentFolderId: { type: ["string", "null"] }, title: { type: "string" }, isPrivate: { type: "boolean", description: "Private folders are not accessible to API keys, MCP, or integrations." }, isAgentReadOnly: { type: "boolean", description: "Broad API key scopes can read but not create or edit in this folder." }, createdAt: { type: "string" }, updatedAt: { type: "string" } } },
      FoldersResponse: { type: "object", required: ["folders"], properties: { folders: { type: "array", items: { $ref: "#/components/schemas/Folder" } } } },
      FolderResponse: { type: "object", required: ["folder"], properties: { folder: { $ref: "#/components/schemas/Folder" } } },
      CreateFolderRequest: { type: "object", required: ["title"], properties: { title: { type: "string" }, parentFolderId: { type: ["string", "null"], description: "Optional parent folder. Maximum depth is five folder levels." } } },
      Note: { type: "object", required: ["id", "folderId", "title", "content", "type", "isApiEditable", "createdAt", "updatedAt"], properties: { id: { type: "string" }, folderId: { type: "string" }, title: { type: "string" }, content: { type: "string" }, type: { type: "string", enum: ["note", "template"] }, isApiEditable: { type: "boolean" }, updatedByActorType: { type: ["string", "null"] }, updatedByActorId: { type: ["string", "null"] }, createdAt: { type: "string" }, updatedAt: { type: "string" }, folderTitle: { type: "string" } } },
      NoteResponse: { type: "object", required: ["note", "contentHash"], properties: { note: { $ref: "#/components/schemas/Note" }, contentHash: { type: "string" } } },
      SearchNotesResponse: { type: "object", required: ["notes"], properties: { notes: { type: "array", items: { $ref: "#/components/schemas/Note" } } } },
      Tag: { type: "object", required: ["id", "name", "normalizedName"], properties: { id: { type: "string" }, name: { type: "string" }, normalizedName: { type: "string" }, noteCount: { type: "integer" } } },
      TagsResponse: { type: "object", required: ["tags"], properties: { tags: { type: "array", items: { $ref: "#/components/schemas/Tag" } } } },
      UpdateTagsRequest: { type: "object", required: ["tags"], properties: { tags: { type: "array", items: { type: "string" } } } },
      CreateNoteRequest: { type: "object", required: ["folderId"], properties: { folderId: { type: "string" }, title: { type: "string" }, content: { type: "string" } } },
      NumberedLine: { type: "object", required: ["line", "text"], properties: { line: { type: "integer" }, text: { type: "string" } } },
      LinesResponse: { type: "object", properties: { noteId: { type: "string" }, contentHash: { type: "string" }, from: { type: "integer" }, to: { type: "integer" }, lineCount: { type: "integer" }, lines: { type: "array", items: { $ref: "#/components/schemas/NumberedLine" } } } },
      LineSearchMatch: { type: "object", properties: { noteId: { type: "string" }, folderId: { type: "string" }, title: { type: "string" }, line: { type: "integer" }, column: { type: "integer" }, text: { type: "string" }, before: { type: "array", items: { $ref: "#/components/schemas/NumberedLine" } }, after: { type: "array", items: { $ref: "#/components/schemas/NumberedLine" } } } },
      LineSearchResponse: { type: "object", required: ["query", "matches"], properties: { query: { type: "string" }, matches: { type: "array", items: { $ref: "#/components/schemas/LineSearchMatch" } } } },
      NoteEvent: { type: "object", properties: { id: { type: "string" }, noteId: { type: "string" }, userId: { type: "string" }, actorType: { type: "string" }, actorId: { type: ["string", "null"] }, eventType: { type: "string" }, summary: { type: "string" }, beforeHash: { type: ["string", "null"] }, afterHash: { type: ["string", "null"] }, createdAt: { type: "string" } } },
      NoteEventsResponse: { type: "object", required: ["noteId", "events"], properties: { noteId: { type: "string" }, events: { type: "array", items: { $ref: "#/components/schemas/NoteEvent" } } } },
      NoteLink: { type: "object", required: ["id", "sourceNoteId", "targetNoteId", "targetTitle", "label", "linkType", "createdAt", "updatedAt"], properties: { id: { type: "string" }, sourceNoteId: { type: "string" }, targetNoteId: { type: ["string", "null"] }, targetTitle: { type: "string" }, label: { type: ["string", "null"] }, linkType: { type: "string", enum: ["wikilink", "internal-url", "markdown-internal-url"] }, createdAt: { type: "string" }, updatedAt: { type: "string" } } },
      LinksResponse: { type: "object", required: ["noteId", "links"], properties: { noteId: { type: "string" }, links: { type: "array", items: { $ref: "#/components/schemas/NoteLink" } } } },
      Backlink: { type: "object", required: ["id", "sourceNoteId", "sourceTitle", "sourceFolderId", "targetTitle", "label", "linkType", "createdAt", "updatedAt"], properties: { id: { type: "string" }, sourceNoteId: { type: "string" }, sourceTitle: { type: "string" }, sourceFolderId: { type: "string" }, targetTitle: { type: "string" }, label: { type: ["string", "null"] }, linkType: { type: "string", enum: ["wikilink", "internal-url", "markdown-internal-url"] }, createdAt: { type: "string" }, updatedAt: { type: "string" } } },
      BacklinksResponse: { type: "object", required: ["noteId", "backlinks"], properties: { noteId: { type: "string" }, backlinks: { type: "array", items: { $ref: "#/components/schemas/Backlink" } } } },
      DocumentSection: { type: "object", required: ["id", "heading", "level", "from", "to", "contentFrom", "contentTo"], properties: { id: { type: "string" }, heading: { type: "string" }, level: { type: "integer" }, from: { type: "integer" }, to: { type: "integer" }, contentFrom: { type: "integer" }, contentTo: { type: "integer" } } },
      OutlineResponse: { type: "object", required: ["noteId", "contentHash", "sections"], properties: { noteId: { type: "string" }, contentHash: { type: "string" }, sections: { type: "array", items: { $ref: "#/components/schemas/DocumentSection" } } } },
      SectionResponse: { type: "object", required: ["noteId", "contentHash", "section"], properties: { noteId: { type: "string" }, contentHash: { type: "string" }, section: { allOf: [{ $ref: "#/components/schemas/DocumentSection" }, { type: "object", properties: { markdown: { type: "string" }, content: { type: "string" } } }] } } },
      DocumentEdit: { oneOf: [{ type: "object", required: ["type", "text"], properties: { type: { const: "append" }, text: { type: "string" } } }, { type: "object", required: ["type", "oldText", "newText"], properties: { type: { const: "replace_text" }, oldText: { type: "string" }, newText: { type: "string" } } }, { type: "object", required: ["type", "from", "to", "text"], properties: { type: { const: "replace_range" }, from: { type: "integer" }, to: { type: "integer" }, text: { type: "string" } } }] },
      EditNoteRequest: { type: "object", required: ["edits"], properties: { baseHash: { type: "string" }, edits: { type: "array", minItems: 1, items: { $ref: "#/components/schemas/DocumentEdit" } } } },
    },
  },
} as const;
